### PR TITLE
floating navbar made responsive using hamburger

### PR DESCRIPTION
**Pull request by ParvamShah1**
Updated Pull Request with Major Revisions

Hi @NiranjanKumar001 ,

I hope you're doing well. Following your feedback on my previous pull request, I've made substantial updates to address all the points you raised. I've carefully reviewed and revised the code to ensure it aligns with the project requirements and coding standards.

Please consider this updated pull request for review. I appreciate your time and feedback, and I look forward to hearing from you.

Thank you for your consideration!
issue #29 .
Best regards,

Here are few images for your reference,
image
image

### CODE REVIEW

**Comment by NiranjanKumar001** [comment]
Screenshot 2024-10-13 174304
Screenshot 2024-10-13 174319
you fixed for smaller devices but messed larger one . @ParvamShah1

**Comment by ParvamShah1** [comment]
Hi @NiranjanKumar001 ,
As you asked i have updated the desktop view as it was before and hamburger will work the same way as it worked before .
Please review the changes and consider merging my pull request ,there have been a lot of efforts into this.
Thanks for your patience and consideration.
Here are few images for your reference ,
image
image

**Comment by NiranjanKumar001** [comment]
@ParvamShah1 Crazzy after so many rejection didnt gave and finally did it .GREAT !!

**Comment by ParvamShah1** [comment]
Thanks for your cooperation !

**Pull request merged**
